services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $cacheDir: '%kernel.cache_dir%'
            $isDebug: '%kernel.debug%'

    Becklyn\Cache\:
        resource: '../../*'
        exclude: '../../{Resources,BecklynCacheBundle.php}'

    Becklyn\Cache\Cache\CacheFactory:
        arguments:
            $appPool: '@cache.app'
            $systemPool: '@cache.system'
        calls:
            -   method: setConfigCacheFactory
                arguments:
                    - '@config_cache_factory'
